In [36]:
import ipfshttpclient
import tensorflow as tf
import torch
import io
import numpy as np
import json
client = ipfshttpclient.connect('/ip4/127.0.0.1/tcp/5001/http')
# files = client.ls()

c:\Users\afaan\Desktop\IDEAS\Repo\FL_Tensorflow_MNIST\env\lib\site-packages\ipfshttpclient\client\__init__.py:75: VersionMismatch: Unsupported daemon version '0.18.1' (not in range: 0.5.0 ≤ … < 0.9.0)
  warnings.warn(exceptions.VersionMismatch(version, minimum, maximum))


In [37]:
model_hash = 'QmY1tk29Bwv2eGQV9bKAe7QmCxhBExuYtzn7tXVFUx4tgi'
model_bytes = client.cat(model_hash)
model_path = 'mnist_model_with_weights.h5'
with open(model_path, 'wb') as f:
    f.write(model_bytes)
model = tf.keras.models.load_model(model_path)
print("Done Model!!!!!!")
print(model.get_weights())


Done Model!!!!!!
[array([[[[-3.05125560e-03,  1.01164803e-01,  1.37577608e-01,
           3.05680633e-01, -8.13007802e-02, -4.13529992e-01,
           2.11013436e-01,  5.84210493e-02, -6.21973574e-01,
          -8.91928002e-02,  5.74861504e-02, -6.07292414e-01,
          -1.47099450e-01,  2.61561811e-01,  1.40060872e-01,
          -2.32800588e-01,  4.22111541e-01, -1.59217585e-02,
          -5.91205180e-01, -8.13530207e-01,  8.01920965e-02,
           3.73617150e-02, -4.35752928e-01, -5.86693406e-01,
          -2.12890655e-01,  1.86650559e-01, -1.15163885e-01,
          -1.07781339e+00,  9.27725136e-02,  2.28235632e-01,
           9.64761060e-03,  2.63028860e-01]],

        [[-2.23880172e-01, -2.60524601e-02,  5.87091744e-02,
          -1.90119460e-01,  2.69631833e-01,  1.97128773e-01,
           1.00589052e-01,  1.04305804e-01, -6.02251112e-01,
           1.82531625e-01, -3.30560625e-01, -5.66058457e-01,
          -6.19803786e-01,  1.23571567e-01,  5.20462811e-01,
           1.2862199

In [38]:
# model_hash = 'QmZaeFLUPJZopTvKWsuji2Q5RPWaTLBRtpCoBbDM6sDyqM'
# model_bytes = client.cat(model_hash)
# model = torch.jit.load(io.BytesIO(model_bytes))
# print("Done Model!!!!!!")
# print(model)






In [40]:
opt = model.optimizer
opt_config = opt.get_config()
opt_config_converted = {}
for key, value in opt_config.items():
    if isinstance(value, np.float32):
        value = float(value)
    opt_config_converted[key] = value
opt_dict = {'name': opt.__class__.__name__, 'config': opt_config_converted}
opt_str = json.dumps(opt_dict)

        # Serialize optimizer state as a dictionary
opt_state = {'name': opt.__class__.__name__, 'state_dict': opt.variables()}
print(opt_state)
        

{'name': 'Adam', 'state_dict': ListWrapper([<tf.Variable 'iteration:0' shape=() dtype=int64, numpy=9375>, <tf.Variable 'm/conv2d/kernel:0' shape=(3, 3, 1, 32) dtype=float32, numpy=
array([[[[ 3.67598934e-03, -1.42513396e-04,  4.78228525e-04,
           7.71636423e-03,  1.85247269e-02,  2.17498397e-03,
           1.72884174e-04, -1.22895441e-03,  2.90758605e-03,
           8.59788153e-04,  1.93504430e-03,  1.10566523e-02,
           3.18977423e-03,  6.01752941e-03,  2.51706643e-03,
          -8.10838421e-04,  1.23675456e-02, -6.17090100e-03,
           2.27282275e-04, -3.97216034e-04, -1.57766114e-03,
           5.61132515e-03,  5.56680048e-03,  2.60721630e-04,
           1.18783489e-03,  5.15429769e-03, -2.04627417e-04,
           3.60958627e-04, -1.95660675e-03, -1.48702995e-03,
           2.98408139e-03,  6.64174603e-03]],

        [[ 2.76256911e-03, -4.34402551e-04,  9.04230517e-04,
           6.33044261e-03,  2.14836299e-02,  3.11740860e-03,
           8.72543489e-04, -1.26554212e-

In [43]:
import tensorflow as tf

# Load the MNIST dataset
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

# Reshape the input data
x_train = x_train.reshape((x_train.shape[0], 28*28))

# Normalize the input data
x_train = x_train / 255.0

# One-hot encode the labels
y_train = tf.keras.utils.to_categorical(y_train)

# Define the model architecture
model = tf.keras.Sequential([
  tf.keras.layers.Dense(64, activation='relu', input_shape=(784,)),
  tf.keras.layers.Dense(10, activation='softmax')
])

# Compile the model
model.compile(optimizer=tf.keras.optimizers.Adam(),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Train the model
model.fit(x_train, y_train, epochs=10)

# Save the model
model.save('path/to/model')


Epoch 1/10
1875/1875 [==============================] - 9s 3ms/step - loss: 0.2943 - accuracy: 0.9172
Epoch 2/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1370 - accuracy: 0.9604
Epoch 3/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1006 - accuracy: 0.9703
Epoch 4/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0796 - accuracy: 0.9761
Epoch 5/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0658 - accuracy: 0.9802
Epoch 6/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0546 - accuracy: 0.9835
Epoch 7/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0470 - accuracy: 0.9853
Epoch 8/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0398 - accuracy: 0.9878
Epoch 9/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0345 - accuracy: 0.9891
Epoch 10/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.029

INFO:tensorflow:Assets written to: path/to/model\assets


INFO:tensorflow:Assets written to: path/to/model\assets


In [45]:
import tensorflow as tf
import numpy as np

class Client():
    def __init__(self, num_workers):
        self.num_workers = num_workers
        
    def average(self, state_dicts):
        final_dict = {}
        for key in state_dicts[0]:
            final_dict[key] = tf.identity(state_dicts[0][key])
            for i in range(1, self.num_workers):
                final_dict[key] += tf.identity(state_dicts[i][key])
            final_dict[key] /= self.num_workers

        return final_dict





In [49]:
import tensorflow_federated as tff

# Test TFF installation
print(f'TensorFlow Federated version: {tff.__version__}')

ModuleNotFoundError: No module named 'tensorflow_federated'

In [47]:
# Example usage
num_workers = 3
state_dicts = [
    {"weight": tf.constant([1.0, 2.0, 3.0])},
    {"weight": tf.constant([4.0, 5.0, 6.0])},
    {"weight": tf.constant([7.0, 8.0, 9.0])}
]
print(state_dicts)
client = Client(num_workers)
averaged_state_dict = client.average(state_dicts)

print(averaged_state_dict) # Output: {'weight': <tf.Tensor: shape=(3,), dtype=float32, numpy=array([4., 5., 6.], dtype=float32)>}

[{'weight': <tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>}, {'weight': <tf.Tensor: shape=(3,), dtype=float32, numpy=array([4., 5., 6.], dtype=float32)>}, {'weight': <tf.Tensor: shape=(3,), dtype=float32, numpy=array([7., 8., 9.], dtype=float32)>}]
{'weight': <tf.Tensor: shape=(3,), dtype=float32, numpy=array([4., 5., 6.], dtype=float32)>}


In [4]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Conv2D, MaxPooling2D
from tensorflow.keras.optimizers import SGD
from tensorflow.keras.datasets import mnist
from sklearn.model_selection import train_test_split

# Load the MNIST dataset and preprocess
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0
x_train = x_train[..., tf.newaxis]
x_test = x_test[..., tf.newaxis]

y_train = tf.keras.utils.to_categorical(y_train, 10)
y_test = tf.keras.utils.to_categorical(y_test, 10)

# Split the training data into "local" datasets
n_devices = 5
# print("X train",x_train)
# print("Y train",y_train))\
local_data = np.array_split(list(zip(x_train, y_train)), n_devices)

# Create the global model architecture
def create_model():
    model = Sequential([
        Conv2D(32, kernel_size=(3, 3), activation='relu', input_shape=(28, 28, 1)),
        MaxPooling2D(pool_size=(2, 2)),
        Conv2D(64, kernel_size=(3, 3), activation='relu'),
        MaxPooling2D(pool_size=(2, 2)),
        Flatten(),
        Dense(128, activation='relu'),
        Dense(10, activation='softmax')
    ])
    model.compile(loss='categorical_crossentropy', optimizer=SGD(lr=0.01), metrics=['accuracy'])
    return model

global_model = create_model()

# Federated learning parameters
n_rounds = 10
n_local_epochs = 1
batch_size = 32

# Federated learning loop
for round in range(n_rounds):
    print(f"Federated Learning Round: {round + 1}")

    local_models = []

    for i, device_data in enumerate(local_data):
        print(f"Training on device {i + 1}")
        device_x_train, device_y_train = zip(*device_data)
        device_x_train, device_y_train = np.array(device_x_train), np.array(device_y_train)

        local_model = tf.keras.models.clone_model(global_model)
        local_model.set_weights(global_model.get_weights())
        local_model.compile(loss='categorical_crossentropy', optimizer=SGD(lr=0.01), metrics=['accuracy'])
        
        local_model.fit(device_x_train, device_y_train, epochs=n_local_epochs, batch_size=batch_size, verbose=0)
        local_models.append((local_model.get_weights(), len(device_x_train)))

    # Global aggregation
    total_samples = sum([model[1] for model in local_models])
    aggregated_weights = []

    for layer_weights in zip(*[model[0] for model in local_models]):
        layer_sum = np.zeros_like(layer_weights[0])
        for idx, weights in enumerate(layer_weights):
            layer_sum += (local_models[idx][1] / total_samples) * weights
        aggregated_weights.append(layer_sum)

    # Update the global model
    global_model.set_weights(aggregated_weights)

# Evaluate the global model on the test set
global_accuracy = global_model.evaluate(x_test, y_test, verbose=0)[1]
print(f"Global Model Test Accuracy: {global_accuracy}")


X train [[[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (60000, 2) + inhomogeneous part.